[package]
name = "motex"
version = "0.1.0"
authors = ["Parker Burnett <jpburnett@byu.net>"]
edition = "2021"
rust-version = "1.79"
publish = false
readme = "README.md"

[dependencies]
eframe = { version = "0.28.1", features = ["persistence"] }
egui-modal = "0.4.0"
egui-phosphor = "0.5.0"
egui_extras = { version = "0.28.1" , features = ["all_loaders"]}
env_logger = "0.11.5"
variant_count = "1.1.0"
image = "0.25.2"
anyhow = "1.0.86"
byteorder = "1.5.0"
rfd = "0.14.1"
pigment64 = "0.4.5"
strum = "0.26.3"
strum_macros = "0.26.4"